//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/CircleProgress (ui://9leh0eyfgzpr81)
namespace FairyGUI.Baked.Basics
{
    public partial class CircleProgressView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GImage m_bar;

        public CircleProgressView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view CircleProgressView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_bar = (global::FairyGUI.GImage)c.GetChildAt(0);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
