//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/CircleProgress (ui://9leh0eyfgzpr81)
namespace FairyGUI.Baked.Basics
{
    public partial class CircleProgressView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GImage m_bar;

        public CircleProgressView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_bar = (global::FairyGUI.GImage)c.GetChildAt(0);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
