//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Component12 (ui://9leh0eyfmulj7p)
namespace FairyGUI.Baked.Basics
{
    public partial class Component12View
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GImage m_n9;
        public readonly global::FairyGUI.GImage m_n10;
        public readonly global::FairyGUI.GImage m_n11;
        public readonly global::FairyGUI.GImage m_n12;

        public Component12View(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n9 = (global::FairyGUI.GImage)c.GetChildAt(0);
            m_n10 = (global::FairyGUI.GImage)c.GetChildAt(1);
            m_n11 = (global::FairyGUI.GImage)c.GetChildAt(2);
            m_n12 = (global::FairyGUI.GImage)c.GetChildAt(3);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
