//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Text (ui://9leh0eyfnz0z1z)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_TextView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GGraph m_n16;
        public readonly global::FairyGUI.GGraph m_n15;
        public readonly global::FairyGUI.GTextField m_n2;
        public readonly global::FairyGUI.GGraph m_n14;
        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GTextField m_n3;
        public readonly global::FairyGUI.GTextField m_n4;
        public readonly global::FairyGUI.GTextField m_n5;
        public readonly global::FairyGUI.GTextField m_n7;
        public readonly global::FairyGUI.GTextField m_n8;
        public readonly global::FairyGUI.GTextField m_n10;
        public readonly global::FairyGUI.GTextField m_n11;
        public readonly global::FairyGUI.GRichTextField m_n12;
        public readonly global::FairyGUI.GTextField m_n17;
        public readonly global::FairyGUI.GTextField m_n18;
        public readonly global::FairyGUI.GTextField m_n19;
        public readonly global::FairyGUI.GTextField m_n20;
        public readonly global::FairyGUI.GGraph m_n21;
        public readonly global::FairyGUI.GTextInput m_n22;
        public readonly global::FairyGUI.GTextField m_n23;
        public readonly global::FairyGUI.GTextField m_n24;
        public readonly global::FairyGUI.GButton m_n25;
        public readonly global::FairyGUI.GTextField m_n26;
        public readonly global::FairyGUI.GTextField m_n27;
        public readonly global::FairyGUI.GTextField m_n28;

        public Demo_TextView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_TextView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n16 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_n15 = (global::FairyGUI.GGraph)c.GetChildAt(1);
            m_n2 = (global::FairyGUI.GTextField)c.GetChildAt(2);
            m_n14 = (global::FairyGUI.GGraph)c.GetChildAt(3);
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n3 = (global::FairyGUI.GTextField)c.GetChildAt(5);
            m_n4 = (global::FairyGUI.GTextField)c.GetChildAt(6);
            m_n5 = (global::FairyGUI.GTextField)c.GetChildAt(7);
            m_n7 = (global::FairyGUI.GTextField)c.GetChildAt(8);
            m_n8 = (global::FairyGUI.GTextField)c.GetChildAt(9);
            m_n10 = (global::FairyGUI.GTextField)c.GetChildAt(10);
            m_n11 = (global::FairyGUI.GTextField)c.GetChildAt(11);
            m_n12 = (global::FairyGUI.GRichTextField)c.GetChildAt(12);
            m_n17 = (global::FairyGUI.GTextField)c.GetChildAt(13);
            m_n18 = (global::FairyGUI.GTextField)c.GetChildAt(14);
            m_n19 = (global::FairyGUI.GTextField)c.GetChildAt(15);
            m_n20 = (global::FairyGUI.GTextField)c.GetChildAt(16);
            m_n21 = (global::FairyGUI.GGraph)c.GetChildAt(17);
            m_n22 = (global::FairyGUI.GTextInput)c.GetChildAt(18);
            m_n23 = (global::FairyGUI.GTextField)c.GetChildAt(19);
            m_n24 = (global::FairyGUI.GTextField)c.GetChildAt(20);
            m_n25 = (global::FairyGUI.GButton)c.GetChildAt(21);
            m_n26 = (global::FairyGUI.GTextField)c.GetChildAt(22);
            m_n27 = (global::FairyGUI.GTextField)c.GetChildAt(23);
            m_n28 = (global::FairyGUI.GTextField)c.GetChildAt(24);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
