//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Drag&Drop (ui://9leh0eyfgx2b78)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_Drag_DropView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GButton m_a;
        public readonly global::FairyGUI.GButton m_b;
        public readonly global::FairyGUI.GButton m_c;
        public readonly global::FairyGUI.GTextField m_n3;
        public readonly global::FairyGUI.GTextField m_n4;
        public readonly global::FairyGUI.GTextField m_n6;
        public readonly global::FairyGUI.GGraph m_n7;
        public readonly global::FairyGUI.GButton m_d;

        public Demo_Drag_DropView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_Drag_DropView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_a = (global::FairyGUI.GButton)c.GetChildAt(0);
            m_b = (global::FairyGUI.GButton)c.GetChildAt(1);
            m_c = (global::FairyGUI.GButton)c.GetChildAt(2);
            m_n3 = (global::FairyGUI.GTextField)c.GetChildAt(3);
            m_n4 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n6 = (global::FairyGUI.GTextField)c.GetChildAt(5);
            m_n7 = (global::FairyGUI.GGraph)c.GetChildAt(6);
            m_d = (global::FairyGUI.GButton)c.GetChildAt(7);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
