//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Grid (ui://9leh0eyfc2z47l)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_GridView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GGraph m_n27;
        public readonly global::FairyGUI.GImage m_n18;
        public readonly global::FairyGUI.GList m_list1;
        public readonly global::FairyGUI.GTextField m_n20;
        public readonly global::FairyGUI.GTextField m_n21;
        public readonly global::FairyGUI.GTextField m_n23;
        public readonly global::FairyGUI.GTextField m_n24;
        public readonly global::FairyGUI.GGroup m_n25;
        public readonly global::FairyGUI.GGraph m_n28;
        public readonly global::FairyGUI.GImage m_n29;
        public readonly global::FairyGUI.GList m_list2;
        public readonly global::FairyGUI.GTextField m_n32;
        public readonly global::FairyGUI.GTextField m_n33;
        public readonly global::FairyGUI.GTextField m_n34;
        public readonly global::FairyGUI.GGroup m_n35;

        public Demo_GridView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n27 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_n18 = (global::FairyGUI.GImage)c.GetChildAt(1);
            m_list1 = (global::FairyGUI.GList)c.GetChildAt(2);
            m_n20 = (global::FairyGUI.GTextField)c.GetChildAt(3);
            m_n21 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n23 = (global::FairyGUI.GTextField)c.GetChildAt(5);
            m_n24 = (global::FairyGUI.GTextField)c.GetChildAt(6);
            m_n25 = (global::FairyGUI.GGroup)c.GetChildAt(7);
            m_n28 = (global::FairyGUI.GGraph)c.GetChildAt(8);
            m_n29 = (global::FairyGUI.GImage)c.GetChildAt(9);
            m_list2 = (global::FairyGUI.GList)c.GetChildAt(10);
            m_n32 = (global::FairyGUI.GTextField)c.GetChildAt(11);
            m_n33 = (global::FairyGUI.GTextField)c.GetChildAt(12);
            m_n34 = (global::FairyGUI.GTextField)c.GetChildAt(13);
            m_n35 = (global::FairyGUI.GGroup)c.GetChildAt(14);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
