//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Loader (ui://9leh0eyfwa8u2s)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_LoaderView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GLoader m_n1;
        public readonly global::FairyGUI.GLoader m_n2;
        public readonly global::FairyGUI.GLoader m_n3;
        public readonly global::FairyGUI.GLoader m_n4;
        public readonly global::FairyGUI.GLoader m_n5;

        public Demo_LoaderView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_LoaderView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(0);
            m_n1 = (global::FairyGUI.GLoader)c.GetChildAt(1);
            m_n2 = (global::FairyGUI.GLoader)c.GetChildAt(2);
            m_n3 = (global::FairyGUI.GLoader)c.GetChildAt(3);
            m_n4 = (global::FairyGUI.GLoader)c.GetChildAt(4);
            m_n5 = (global::FairyGUI.GLoader)c.GetChildAt(5);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
