//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Relation (ui://9leh0eyfwa8u2x)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_RelationView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public enum c1
        {
            page0 = 0,
            page1 = 1,
        }
        public c1 c1Page
        {
            get { return (c1)com.GetControllerAt(0).selectedIndex; }
            set { com.GetControllerAt(0).selectedIndex = (int)value; }
        }

        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GGraph m_n2;
        public readonly global::FairyGUI.GGraph m_n1;
        public readonly global::FairyGUI.GButton m_n5;
        public readonly global::FairyGUI.GGraph m_n7;
        public readonly global::FairyGUI.GGraph m_n8;
        public readonly global::FairyGUI.GGraph m_n9;
        public readonly global::FairyGUI.GGraph m_n10;
        public readonly global::FairyGUI.GGraph m_n12;

        public Demo_RelationView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_RelationView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(0);
            m_n2 = (global::FairyGUI.GGraph)c.GetChildAt(1);
            m_n1 = (global::FairyGUI.GGraph)c.GetChildAt(2);
            m_n5 = (global::FairyGUI.GButton)c.GetChildAt(3);
            m_n7 = (global::FairyGUI.GGraph)c.GetChildAt(4);
            m_n8 = (global::FairyGUI.GGraph)c.GetChildAt(5);
            m_n9 = (global::FairyGUI.GGraph)c.GetChildAt(6);
            m_n10 = (global::FairyGUI.GGraph)c.GetChildAt(7);
            m_n12 = (global::FairyGUI.GGraph)c.GetChildAt(8);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                case 0: c1Page = (c1)pageIndex; break;
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
