//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_List (ui://9leh0eyfzd9g4g)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ListView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GList m_n0;
        public readonly global::FairyGUI.GTextField m_n1;
        public readonly global::FairyGUI.GTextField m_n2;
        public readonly global::FairyGUI.GList m_n4;
        public readonly global::FairyGUI.GTextField m_n5;
        public readonly global::FairyGUI.GList m_n7;
        public readonly global::FairyGUI.GTextField m_n8;
        public readonly global::FairyGUI.GList m_n9;
        public readonly global::FairyGUI.GTextField m_n10;

        public Demo_ListView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_ListView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n0 = (global::FairyGUI.GList)c.GetChildAt(0);
            m_n1 = (global::FairyGUI.GTextField)c.GetChildAt(1);
            m_n2 = (global::FairyGUI.GTextField)c.GetChildAt(2);
            m_n4 = (global::FairyGUI.GList)c.GetChildAt(3);
            m_n5 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n7 = (global::FairyGUI.GList)c.GetChildAt(5);
            m_n8 = (global::FairyGUI.GTextField)c.GetChildAt(6);
            m_n9 = (global::FairyGUI.GList)c.GetChildAt(7);
            m_n10 = (global::FairyGUI.GTextField)c.GetChildAt(8);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
