//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Window (ui://9leh0eyfgx2b77)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_WindowView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GButton m_n0;
        public readonly global::FairyGUI.GButton m_n1;

        public Demo_WindowView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n0 = (global::FairyGUI.GButton)c.GetChildAt(0);
            m_n1 = (global::FairyGUI.GButton)c.GetChildAt(1);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
