//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_ProgressBar (ui://9leh0eyfzd9g4f)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ProgressBarView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GProgressBar m_n1;
        public readonly global::FairyGUI.GProgressBar m_n2;
        public readonly global::FairyGUI.GProgressBar m_n3;
        public readonly global::FairyGUI.GProgressBar m_n4;
        public readonly global::FairyGUI.GProgressBar m_n6;
        public readonly global::FairyGUI.GProgressBar m_n7;
        public readonly global::FairyGUI.GProgressBar m_n9;

        public Demo_ProgressBarView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_ProgressBarView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n1 = (global::FairyGUI.GProgressBar)c.GetChildAt(0);
            m_n2 = (global::FairyGUI.GProgressBar)c.GetChildAt(1);
            m_n3 = (global::FairyGUI.GProgressBar)c.GetChildAt(2);
            m_n4 = (global::FairyGUI.GProgressBar)c.GetChildAt(3);
            m_n6 = (global::FairyGUI.GProgressBar)c.GetChildAt(4);
            m_n7 = (global::FairyGUI.GProgressBar)c.GetChildAt(5);
            m_n9 = (global::FairyGUI.GProgressBar)c.GetChildAt(6);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
