//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_MovieClip (ui://9leh0eyfhixt1n)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_MovieClipView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GMovieClip m_n8;
        public readonly global::FairyGUI.GMovieClip m_n13;
        public readonly global::FairyGUI.GMovieClip m_n14;
        public readonly global::FairyGUI.GMovieClip m_n15;
        public readonly global::FairyGUI.GButton m_n18;
        public readonly global::FairyGUI.GMovieClip m_n19;
        public readonly global::FairyGUI.GMovieClip m_n22;

        public Demo_MovieClipView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_MovieClipView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(0);
            m_n8 = (global::FairyGUI.GMovieClip)c.GetChildAt(1);
            m_n13 = (global::FairyGUI.GMovieClip)c.GetChildAt(2);
            m_n14 = (global::FairyGUI.GMovieClip)c.GetChildAt(3);
            m_n15 = (global::FairyGUI.GMovieClip)c.GetChildAt(4);
            m_n18 = (global::FairyGUI.GButton)c.GetChildAt(5);
            m_n19 = (global::FairyGUI.GMovieClip)c.GetChildAt(6);
            m_n22 = (global::FairyGUI.GMovieClip)c.GetChildAt(7);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
