//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Image (ui://9leh0eyfsner1i)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ImageView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GImage m_n6;
        public readonly global::FairyGUI.GImage m_n7;
        public readonly global::FairyGUI.GImage m_n8;
        public readonly global::FairyGUI.GImage m_n9;
        public readonly global::FairyGUI.GTextField m_n11;
        public readonly global::FairyGUI.GImage m_n12;
        public readonly global::FairyGUI.GTextField m_n14;
        public readonly global::FairyGUI.GImage m_n15;
        public readonly global::FairyGUI.GTextField m_n16;
        public readonly global::FairyGUI.GImage m_n17;
        public readonly global::FairyGUI.GImage m_n18;
        public readonly global::FairyGUI.GTextField m_n19;

        public Demo_ImageView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n6 = (global::FairyGUI.GImage)c.GetChildAt(0);
            m_n7 = (global::FairyGUI.GImage)c.GetChildAt(1);
            m_n8 = (global::FairyGUI.GImage)c.GetChildAt(2);
            m_n9 = (global::FairyGUI.GImage)c.GetChildAt(3);
            m_n11 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n12 = (global::FairyGUI.GImage)c.GetChildAt(5);
            m_n14 = (global::FairyGUI.GTextField)c.GetChildAt(6);
            m_n15 = (global::FairyGUI.GImage)c.GetChildAt(7);
            m_n16 = (global::FairyGUI.GTextField)c.GetChildAt(8);
            m_n17 = (global::FairyGUI.GImage)c.GetChildAt(9);
            m_n18 = (global::FairyGUI.GImage)c.GetChildAt(10);
            m_n19 = (global::FairyGUI.GTextField)c.GetChildAt(11);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
