//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Slider (ui://9leh0eyfzd9g4e)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_SliderView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GSlider m_n1;
        public readonly global::FairyGUI.GSlider m_n2;
        public readonly global::FairyGUI.GSlider m_n3;
        public readonly global::FairyGUI.GSlider m_n4;

        public Demo_SliderView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_SliderView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n1 = (global::FairyGUI.GSlider)c.GetChildAt(0);
            m_n2 = (global::FairyGUI.GSlider)c.GetChildAt(1);
            m_n3 = (global::FairyGUI.GSlider)c.GetChildAt(2);
            m_n4 = (global::FairyGUI.GSlider)c.GetChildAt(3);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
