//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Component (ui://9leh0eyft24n7f)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ComponentView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GComponent m_n12;
        public readonly global::FairyGUI.GComponent m_n13;
        public readonly global::FairyGUI.GTextField m_n16;
        public readonly global::FairyGUI.GComponent m_n17;
        public readonly global::FairyGUI.GComponent m_n20;

        public Demo_ComponentView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_ComponentView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(0);
            m_n12 = (global::FairyGUI.GComponent)c.GetChildAt(1);
            m_n13 = (global::FairyGUI.GComponent)c.GetChildAt(2);
            m_n16 = (global::FairyGUI.GTextField)c.GetChildAt(3);
            m_n17 = (global::FairyGUI.GComponent)c.GetChildAt(4);
            m_n20 = (global::FairyGUI.GComponent)c.GetChildAt(5);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
