//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Clip&Scroll (ui://9leh0eyfes412y)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_Clip_ScrollView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GComponent m_n29;
        public readonly global::FairyGUI.GTextField m_n28;
        public readonly global::FairyGUI.GComponent m_n0;
        public readonly global::FairyGUI.GTextField m_n7;
        public readonly global::FairyGUI.GGraph m_n4;
        public readonly global::FairyGUI.GComponent m_n3;
        public readonly global::FairyGUI.GComponent m_n2;
        public readonly global::FairyGUI.GTextField m_n9;
        public readonly global::FairyGUI.GGraph m_n17;
        public readonly global::FairyGUI.GComponent m_n14;
        public readonly global::FairyGUI.GTextField m_n15;
        public readonly global::FairyGUI.GGraph m_n19;
        public readonly global::FairyGUI.GComponent m_n18;
        public readonly global::FairyGUI.GGraph m_n24;
        public readonly global::FairyGUI.GComponent m_n22;

        public Demo_Clip_ScrollView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_Clip_ScrollView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n29 = (global::FairyGUI.GComponent)c.GetChildAt(0);
            m_n28 = (global::FairyGUI.GTextField)c.GetChildAt(1);
            m_n0 = (global::FairyGUI.GComponent)c.GetChildAt(2);
            m_n7 = (global::FairyGUI.GTextField)c.GetChildAt(3);
            m_n4 = (global::FairyGUI.GGraph)c.GetChildAt(4);
            m_n3 = (global::FairyGUI.GComponent)c.GetChildAt(5);
            m_n2 = (global::FairyGUI.GComponent)c.GetChildAt(6);
            m_n9 = (global::FairyGUI.GTextField)c.GetChildAt(7);
            m_n17 = (global::FairyGUI.GGraph)c.GetChildAt(8);
            m_n14 = (global::FairyGUI.GComponent)c.GetChildAt(9);
            m_n15 = (global::FairyGUI.GTextField)c.GetChildAt(10);
            m_n19 = (global::FairyGUI.GGraph)c.GetChildAt(11);
            m_n18 = (global::FairyGUI.GComponent)c.GetChildAt(12);
            m_n24 = (global::FairyGUI.GGraph)c.GetChildAt(13);
            m_n22 = (global::FairyGUI.GComponent)c.GetChildAt(14);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
