//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Controller (ui://9leh0eyfwa8u2v)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ControllerView
    {
        public readonly global::FairyGUI.GComponent com;

        public enum c1
        {
            page0 = 0,
            page1 = 1,
        }
        public c1 c1Page
        {
            get { return (c1)com.GetControllerAt(0).selectedIndex; }
            set { com.GetControllerAt(0).selectedIndex = (int)value; }
        }

        public enum c2
        {
            page0 = 0,
            page1 = 1,
        }
        public c2 c2Page
        {
            get { return (c2)com.GetControllerAt(1).selectedIndex; }
            set { com.GetControllerAt(1).selectedIndex = (int)value; }
        }

        public readonly global::FairyGUI.GGraph m_n3;
        public readonly global::FairyGUI.GTextField m_n0;
        public readonly global::FairyGUI.GGraph m_n5;
        public readonly global::FairyGUI.GTextField m_n6;
        public readonly global::FairyGUI.GImage m_n7;
        public readonly global::FairyGUI.GImage m_n8;
        public readonly global::FairyGUI.GImage m_n9;
        public readonly global::FairyGUI.GMovieClip m_n10;
        public readonly global::FairyGUI.GButton m_n11;
        public readonly global::FairyGUI.GImage m_n13;
        public readonly global::FairyGUI.GImage m_n14;
        public readonly global::FairyGUI.GImage m_n15;
        public readonly global::FairyGUI.GGroup m_n16;
        public readonly global::FairyGUI.GButton m_switchBtn;
        public readonly global::FairyGUI.GTextField m_n17;
        public readonly global::FairyGUI.GGraph m_n18;

        public Demo_ControllerView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n3 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_n0 = (global::FairyGUI.GTextField)c.GetChildAt(1);
            m_n5 = (global::FairyGUI.GGraph)c.GetChildAt(2);
            m_n6 = (global::FairyGUI.GTextField)c.GetChildAt(3);
            m_n7 = (global::FairyGUI.GImage)c.GetChildAt(4);
            m_n8 = (global::FairyGUI.GImage)c.GetChildAt(5);
            m_n9 = (global::FairyGUI.GImage)c.GetChildAt(6);
            m_n10 = (global::FairyGUI.GMovieClip)c.GetChildAt(7);
            m_n11 = (global::FairyGUI.GButton)c.GetChildAt(8);
            m_n13 = (global::FairyGUI.GImage)c.GetChildAt(9);
            m_n14 = (global::FairyGUI.GImage)c.GetChildAt(10);
            m_n15 = (global::FairyGUI.GImage)c.GetChildAt(11);
            m_n16 = (global::FairyGUI.GGroup)c.GetChildAt(12);
            m_switchBtn = (global::FairyGUI.GButton)c.GetChildAt(13);
            m_n17 = (global::FairyGUI.GTextField)c.GetChildAt(14);
            m_n18 = (global::FairyGUI.GGraph)c.GetChildAt(15);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                case 0: c1Page = (c1)pageIndex; break;
                case 1: c2Page = (c2)pageIndex; break;
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
