//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Graph (ui://9leh0eyfhixt1m)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_GraphView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GGraph m_n1;
        public readonly global::FairyGUI.GGraph m_n2;
        public readonly global::FairyGUI.GGraph m_n5;
        public readonly global::FairyGUI.GGraph m_n7;
        public readonly global::FairyGUI.GTextField m_n8;
        public readonly global::FairyGUI.GGraph m_polygon;
        public readonly global::FairyGUI.GGraph m_polygon2;
        public readonly global::FairyGUI.GGraph m_line;
        public readonly global::FairyGUI.GImage m_line3;
        public readonly global::FairyGUI.GGraph m_n4;
        public readonly global::FairyGUI.GGraph m_n6;
        public readonly global::FairyGUI.GGraph m_n11;
        public readonly global::FairyGUI.GGraph m_pie;
        public readonly global::FairyGUI.GImage m_n14;
        public readonly global::FairyGUI.GGraph m_radial;
        public readonly global::FairyGUI.GGraph m_trapezoid;
        public readonly global::FairyGUI.GGraph m_line2;

        public Demo_GraphView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n1 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_n2 = (global::FairyGUI.GGraph)c.GetChildAt(1);
            m_n5 = (global::FairyGUI.GGraph)c.GetChildAt(2);
            m_n7 = (global::FairyGUI.GGraph)c.GetChildAt(3);
            m_n8 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_polygon = (global::FairyGUI.GGraph)c.GetChildAt(5);
            m_polygon2 = (global::FairyGUI.GGraph)c.GetChildAt(6);
            m_line = (global::FairyGUI.GGraph)c.GetChildAt(7);
            m_line3 = (global::FairyGUI.GImage)c.GetChildAt(8);
            m_n4 = (global::FairyGUI.GGraph)c.GetChildAt(9);
            m_n6 = (global::FairyGUI.GGraph)c.GetChildAt(10);
            m_n11 = (global::FairyGUI.GGraph)c.GetChildAt(11);
            m_pie = (global::FairyGUI.GGraph)c.GetChildAt(12);
            m_n14 = (global::FairyGUI.GImage)c.GetChildAt(13);
            m_radial = (global::FairyGUI.GGraph)c.GetChildAt(14);
            m_trapezoid = (global::FairyGUI.GGraph)c.GetChildAt(15);
            m_line2 = (global::FairyGUI.GGraph)c.GetChildAt(16);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
