//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Button (ui://9leh0eyfrpmb1b)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_ButtonView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public enum RadioGroup
        {
            page0 = 0,
            page1 = 1,
            page2 = 2,
        }
        public RadioGroup RadioGroupPage
        {
            get { return (RadioGroup)com.GetControllerAt(0).selectedIndex; }
            set { com.GetControllerAt(0).selectedIndex = (int)value; }
        }

        public enum tab
        {
            page0 = 0,
            page1 = 1,
            page2 = 2,
        }
        public tab tabPage
        {
            get { return (tab)com.GetControllerAt(1).selectedIndex; }
            set { com.GetControllerAt(1).selectedIndex = (int)value; }
        }

        public readonly global::FairyGUI.GGraph m_n26;
        public readonly global::FairyGUI.GButton m_n3;
        public readonly global::FairyGUI.GButton m_n4;
        public readonly global::FairyGUI.GButton m_n5;
        public readonly global::FairyGUI.GButton m_n6;
        public readonly global::FairyGUI.GButton m_n7;
        public readonly global::FairyGUI.GTextField m_n8;
        public readonly global::FairyGUI.GButton m_n11;
        public readonly global::FairyGUI.GButton m_n12;
        public readonly global::FairyGUI.GButton m_n13;
        public readonly global::FairyGUI.GButton m_n15;
        public readonly global::FairyGUI.GButton m_n16;
        public readonly global::FairyGUI.GButton m_n17;
        public readonly global::FairyGUI.GButton m_n18;
        public readonly global::FairyGUI.GButton m_n19;
        public readonly global::FairyGUI.GButton m_n20;
        public readonly global::FairyGUI.GTextField m_n21;
        public readonly global::FairyGUI.GTextField m_n22;
        public readonly global::FairyGUI.GButton m_n23;
        public readonly global::FairyGUI.GButton m_n24;
        public readonly global::FairyGUI.GButton m_n25;
        public readonly global::FairyGUI.GImage m_n29;
        public readonly global::FairyGUI.GImage m_n30;
        public readonly global::FairyGUI.GImage m_n31;
        public readonly global::FairyGUI.GButton m_n32;
        public readonly global::FairyGUI.GTextField m_n33;
        public readonly global::FairyGUI.GButton m_n34;
        public readonly global::FairyGUI.GButton m_n35;
        public readonly global::FairyGUI.GTextField m_n36;
        public readonly global::FairyGUI.GTextField m_n37;
        public readonly global::FairyGUI.GButton m_n38;

        public Demo_ButtonView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_ButtonView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n26 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_n3 = (global::FairyGUI.GButton)c.GetChildAt(1);
            m_n4 = (global::FairyGUI.GButton)c.GetChildAt(2);
            m_n5 = (global::FairyGUI.GButton)c.GetChildAt(3);
            m_n6 = (global::FairyGUI.GButton)c.GetChildAt(4);
            m_n7 = (global::FairyGUI.GButton)c.GetChildAt(5);
            m_n8 = (global::FairyGUI.GTextField)c.GetChildAt(6);
            m_n11 = (global::FairyGUI.GButton)c.GetChildAt(7);
            m_n12 = (global::FairyGUI.GButton)c.GetChildAt(8);
            m_n13 = (global::FairyGUI.GButton)c.GetChildAt(9);
            m_n15 = (global::FairyGUI.GButton)c.GetChildAt(10);
            m_n16 = (global::FairyGUI.GButton)c.GetChildAt(11);
            m_n17 = (global::FairyGUI.GButton)c.GetChildAt(12);
            m_n18 = (global::FairyGUI.GButton)c.GetChildAt(13);
            m_n19 = (global::FairyGUI.GButton)c.GetChildAt(14);
            m_n20 = (global::FairyGUI.GButton)c.GetChildAt(15);
            m_n21 = (global::FairyGUI.GTextField)c.GetChildAt(16);
            m_n22 = (global::FairyGUI.GTextField)c.GetChildAt(17);
            m_n23 = (global::FairyGUI.GButton)c.GetChildAt(18);
            m_n24 = (global::FairyGUI.GButton)c.GetChildAt(19);
            m_n25 = (global::FairyGUI.GButton)c.GetChildAt(20);
            m_n29 = (global::FairyGUI.GImage)c.GetChildAt(21);
            m_n30 = (global::FairyGUI.GImage)c.GetChildAt(22);
            m_n31 = (global::FairyGUI.GImage)c.GetChildAt(23);
            m_n32 = (global::FairyGUI.GButton)c.GetChildAt(24);
            m_n33 = (global::FairyGUI.GTextField)c.GetChildAt(25);
            m_n34 = (global::FairyGUI.GButton)c.GetChildAt(26);
            m_n35 = (global::FairyGUI.GButton)c.GetChildAt(27);
            m_n36 = (global::FairyGUI.GTextField)c.GetChildAt(28);
            m_n37 = (global::FairyGUI.GTextField)c.GetChildAt(29);
            m_n38 = (global::FairyGUI.GButton)c.GetChildAt(30);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                case 0: RadioGroupPage = (RadioGroup)pageIndex; break;
                case 1: tabPage = (tab)pageIndex; break;
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
