//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Demo_Label (ui://9leh0eyfw42o3j)
namespace FairyGUI.Baked.Basics
{
    public partial class Demo_LabelView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GTextField m_n1;
        public readonly global::FairyGUI.GLabel m_frame;
        public readonly global::FairyGUI.GLabel m_n4;
        public readonly global::FairyGUI.GLabel m_n5;

        public Demo_LabelView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view Demo_LabelView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_n1 = (global::FairyGUI.GTextField)c.GetChildAt(0);
            m_frame = (global::FairyGUI.GLabel)c.GetChildAt(1);
            m_n4 = (global::FairyGUI.GLabel)c.GetChildAt(2);
            m_n5 = (global::FairyGUI.GLabel)c.GetChildAt(3);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
