//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/Main (ui://9leh0eyfrpmb1c)
namespace FairyGUI.Baked.Basics
{
    public partial class MainView
    {
        public readonly global::FairyGUI.GComponent com;

        public enum c1
        {
            page0 = 0,
            page1 = 1,
        }
        public c1 c1Page
        {
            get { return (c1)com.GetControllerAt(0).selectedIndex; }
            set { com.GetControllerAt(0).selectedIndex = (int)value; }
        }

        public readonly global::FairyGUI.GGraph m_n26;
        public readonly global::FairyGUI.GComponent m_container;
        public readonly global::FairyGUI.GGraph m_n21;
        public readonly global::FairyGUI.GButton m_btn_Back;
        public readonly global::FairyGUI.GButton m_btn_Button;
        public readonly global::FairyGUI.GButton m_btn_Image;
        public readonly global::FairyGUI.GButton m_btn_Graph;
        public readonly global::FairyGUI.GButton m_btn_MovieClip;
        public readonly global::FairyGUI.GButton m_btn_Depth;
        public readonly global::FairyGUI.GButton m_btn_Loader;
        public readonly global::FairyGUI.GButton m_btn_List;
        public readonly global::FairyGUI.GButton m_btn_ProgressBar;
        public readonly global::FairyGUI.GButton m_btn_Slider;
        public readonly global::FairyGUI.GButton m_btn_ComboBox;
        public readonly global::FairyGUI.GButton m_btn_Clip_Scroll;
        public readonly global::FairyGUI.GButton m_btn_Controller;
        public readonly global::FairyGUI.GButton m_btn_Relation;
        public readonly global::FairyGUI.GButton m_btn_Label;
        public readonly global::FairyGUI.GButton m_btn_Popup;
        public readonly global::FairyGUI.GButton m_btn_Window;
        public readonly global::FairyGUI.GButton m_btn_Drag_Drop;
        public readonly global::FairyGUI.GButton m_btn_Component;
        public readonly global::FairyGUI.GButton m_btn_Grid;
        public readonly global::FairyGUI.GButton m_btn_Text;
        public readonly global::FairyGUI.GGroup m_btns;
        public readonly global::FairyGUI.GTextField m_n24;

        public MainView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n26 = (global::FairyGUI.GGraph)c.GetChildAt(0);
            m_container = (global::FairyGUI.GComponent)c.GetChildAt(1);
            m_n21 = (global::FairyGUI.GGraph)c.GetChildAt(2);
            m_btn_Back = (global::FairyGUI.GButton)c.GetChildAt(3);
            m_btn_Button = (global::FairyGUI.GButton)c.GetChildAt(4);
            m_btn_Image = (global::FairyGUI.GButton)c.GetChildAt(5);
            m_btn_Graph = (global::FairyGUI.GButton)c.GetChildAt(6);
            m_btn_MovieClip = (global::FairyGUI.GButton)c.GetChildAt(7);
            m_btn_Depth = (global::FairyGUI.GButton)c.GetChildAt(8);
            m_btn_Loader = (global::FairyGUI.GButton)c.GetChildAt(9);
            m_btn_List = (global::FairyGUI.GButton)c.GetChildAt(10);
            m_btn_ProgressBar = (global::FairyGUI.GButton)c.GetChildAt(11);
            m_btn_Slider = (global::FairyGUI.GButton)c.GetChildAt(12);
            m_btn_ComboBox = (global::FairyGUI.GButton)c.GetChildAt(13);
            m_btn_Clip_Scroll = (global::FairyGUI.GButton)c.GetChildAt(14);
            m_btn_Controller = (global::FairyGUI.GButton)c.GetChildAt(15);
            m_btn_Relation = (global::FairyGUI.GButton)c.GetChildAt(16);
            m_btn_Label = (global::FairyGUI.GButton)c.GetChildAt(17);
            m_btn_Popup = (global::FairyGUI.GButton)c.GetChildAt(18);
            m_btn_Window = (global::FairyGUI.GButton)c.GetChildAt(19);
            m_btn_Drag_Drop = (global::FairyGUI.GButton)c.GetChildAt(20);
            m_btn_Component = (global::FairyGUI.GButton)c.GetChildAt(21);
            m_btn_Grid = (global::FairyGUI.GButton)c.GetChildAt(22);
            m_btn_Text = (global::FairyGUI.GButton)c.GetChildAt(23);
            m_btns = (global::FairyGUI.GGroup)c.GetChildAt(24);
            m_n24 = (global::FairyGUI.GTextField)c.GetChildAt(25);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                case 0: c1Page = (c1)pageIndex; break;
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
