//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/ScrollBar_HZ (ui://9leh0eyfi3s65i)
namespace FairyGUI.Baked.Basics
{
    public partial class ScrollBar_HZView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GImage m_n0;
        public readonly global::FairyGUI.GGraph m_bar;
        public readonly global::FairyGUI.GButton m_arrow1;
        public readonly global::FairyGUI.GButton m_arrow2;
        public readonly global::FairyGUI.GButton m_grip;

        public ScrollBar_HZView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n0 = (global::FairyGUI.GImage)c.GetChildAt(0);
            m_bar = (global::FairyGUI.GGraph)c.GetChildAt(1);
            m_arrow1 = (global::FairyGUI.GButton)c.GetChildAt(2);
            m_arrow2 = (global::FairyGUI.GButton)c.GetChildAt(3);
            m_grip = (global::FairyGUI.GButton)c.GetChildAt(4);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
