//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/WindowA (ui://9leh0eyfl6f473)
namespace FairyGUI.Baked.Basics
{
    public partial class WindowAView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GLabel m_frame;
        public readonly global::FairyGUI.GComboBox m_n2;
        public readonly global::FairyGUI.GButton m_n5;
        public readonly global::FairyGUI.GList m_n6;

        public WindowAView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_frame = (global::FairyGUI.GLabel)c.GetChildAt(0);
            m_n2 = (global::FairyGUI.GComboBox)c.GetChildAt(1);
            m_n5 = (global::FairyGUI.GButton)c.GetChildAt(2);
            m_n6 = (global::FairyGUI.GList)c.GetChildAt(3);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
