//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: Basics/WindowB (ui://9leh0eyf796x7a)
namespace FairyGUI.Baked.Basics
{
    public partial class WindowBView
    {
        public readonly global::FairyGUI.GComponent com;
        public const ulong BakedSourceHash = 0x668D00CB44B58CDDUL;

        public readonly global::FairyGUI.GLabel m_frame;
        public readonly global::FairyGUI.GImage m_n7;
        public readonly global::FairyGUI.GTextField m_n10;
        public readonly global::FairyGUI.GProgressBar m_n12;

        public WindowBView(global::FairyGUI.GComponent c)
        {
            com = c;
            var __pi = c.packageItem;
            if (__pi != null && __pi.owner != null && __pi.owner.sourceHash != BakedSourceHash)
                global::UnityEngine.Debug.LogWarning("FQS view WindowBView is stale: package 'Basics' changed since generation — child indices/types may be wrong. Re-bake via Tools/FairyGUI/Bake Packages (FQS).");
            m_frame = (global::FairyGUI.GLabel)c.GetChildAt(0);
            m_n7 = (global::FairyGUI.GImage)c.GetChildAt(1);
            m_n10 = (global::FairyGUI.GTextField)c.GetChildAt(2);
            m_n12 = (global::FairyGUI.GProgressBar)c.GetChildAt(3);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
