using System.Collections.Generic;
using System.IO;
using System.Text;
using FairyGUI;

namespace FairyGUIEditor
{
    /// <summary>
    /// M8-3: generates one strongly-typed view FACADE per exported component —
    /// nested page enums per controller (rename/delete a page in the editor and
    /// user code fails at COMPILE time), typed m_ child references bound once
    /// at construction, and an int-switch bridge for untyped callers. The
    /// facade wraps the untouched runtime (GComponent/Controller by index);
    /// runtime package loading and the string APIs keep working unchanged.
    /// Writes are content-compared: an unchanged re-bake writes nothing.
    /// </summary>
    public static class FqsViewGenerator
    {
        static readonly HashSet<string> CsKeywords = new HashSet<string>
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked",
            "class","const","continue","decimal","default","delegate","do","double","else",
            "enum","event","explicit","extern","false","finally","fixed","float","for",
            "foreach","goto","if","implicit","in","int","interface","internal","is","lock",
            "long","namespace","new","null","object","operator","out","override","params",
            "private","protected","public","readonly","ref","return","sbyte","sealed",
            "short","sizeof","stackalloc","static","string","struct","switch","this",
            "throw","true","try","typeof","uint","ulong","unchecked","unsafe","ushort",
            "using","virtual","void","volatile","while",
        };

        /// <summary>
        /// FairyGUI name -> C# identifier: punctuation folds to '_', digit
        /// prefixes escape, keywords get '@', and collisions after folding
        /// dedup with _2/_3 within the given scope set.
        /// </summary>
        public static string Identifier(string raw, HashSet<string> used)
        {
            var b = new StringBuilder(raw?.Length ?? 1);
            if (!string.IsNullOrEmpty(raw))
                foreach (char ch in raw)
                    b.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            string id = b.Length > 0 ? b.ToString() : "_";
            if (char.IsDigit(id[0]))
                id = "_" + id;
            if (CsKeywords.Contains(id))
                id = "@" + id;
            if (used != null)
            {
                string baseId = id;
                int n = 2;
                while (!used.Add(id))
                    id = baseId + "_" + n++;
            }
            return id;
        }

        /// <summary>
        /// Generates the facade source for one live component instance. The
        /// class name deduplicates within usedClassNames (duplicate exported
        /// names in one package fold to the same identifier otherwise).
        /// </summary>
        public static string GenerateSource(UIPackage pkg, PackageItem item, GComponent inst,
            HashSet<string> usedClassNames, out string className)
        {
            className = Identifier(item.name, usedClassNames) + "View";
            string ns = "FairyGUI.Baked." + Identifier(pkg.name, null);
            //member scope: 'com' is reserved by the wrapper field
            var used = new HashSet<string> { "com", className };

            var sb = new StringBuilder(2048);
            sb.Append("//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)\n");
            sb.Append("//source: ").Append(pkg.name).Append('/').Append(item.name)
              .Append(" (ui://").Append(pkg.id).Append(item.id).Append(")\n");
            sb.Append("namespace ").Append(ns).Append("\n{\n");
            sb.Append("    public partial class ").Append(className).Append("\n    {\n");
            sb.Append("        public readonly global::FairyGUI.GComponent com;\n");

            var ctrls = inst.Controllers;
            var ctrlIds = new List<string>(ctrls.Count);
            for (int ci = 0; ci < ctrls.Count; ci++)
            {
                Controller ctrl = ctrls[ci];
                string ctrlId = Identifier(ctrl.name, used);
                used.Add(ctrlId + "Page");
                ctrlIds.Add(ctrlId);

                sb.Append("\n        public enum ").Append(ctrlId).Append("\n        {\n");
                var pageUsed = new HashSet<string>();
                for (int p = 0; p < ctrl.pageCount; p++)
                {
                    string pn = ctrl.GetPageName(p);
                    string member = string.IsNullOrEmpty(pn)
                        ? Identifier("page" + p, pageUsed)
                        : Identifier(pn, pageUsed);
                    sb.Append("            ").Append(member).Append(" = ").Append(p).Append(",\n");
                }
                sb.Append("        }\n");
                sb.Append("        public ").Append(ctrlId).Append(' ').Append(ctrlId).Append("Page\n        {\n");
                sb.Append("            get { return (").Append(ctrlId).Append(")com.GetControllerAt(").Append(ci).Append(").selectedIndex; }\n");
                sb.Append("            set { com.GetControllerAt(").Append(ci).Append(").selectedIndex = (int)value; }\n");
                sb.Append("        }\n");
            }

            //typed child references, bound once by index (regeneration keeps
            //indices in sync with the package; reorder -> re-bake)
            var fields = new List<(string id, string type, int index)>();
            for (int i = 0; i < inst.numChildren; i++)
            {
                GObject child = inst.GetChildAt(i);
                if (string.IsNullOrEmpty(child.name))
                    continue;
                string fid = Identifier("m_" + child.name, used);
                string type = "global::" + child.GetType().FullName.Replace('+', '.');
                fields.Add((fid, type, i));
            }
            if (fields.Count > 0)
                sb.Append('\n');
            foreach (var f in fields)
                sb.Append("        public readonly ").Append(f.type).Append(' ').Append(f.id).Append(";\n");

            sb.Append("\n        public ").Append(className).Append("(global::FairyGUI.GComponent c)\n        {\n");
            sb.Append("            com = c;\n");
            foreach (var f in fields)
                sb.Append("            ").Append(f.id).Append(" = (").Append(f.type)
                  .Append(")c.GetChildAt(").Append(f.index).Append(");\n");
            sb.Append("        }\n");

            //int-switch bridge: untyped callers reach the typed layer without
            //reflection (and out-of-range indices keep the runtime behavior)
            sb.Append("\n        public void SetPage(int controllerIndex, int pageIndex)\n        {\n");
            sb.Append("            switch (controllerIndex)\n            {\n");
            for (int ci = 0; ci < ctrlIds.Count; ci++)
                sb.Append("                case ").Append(ci).Append(": ").Append(ctrlIds[ci])
                  .Append("Page = (").Append(ctrlIds[ci]).Append(")pageIndex; break;\n");
            sb.Append("                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;\n");
            sb.Append("            }\n        }\n");

            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        /// <summary>Content-compared write: idempotent re-bakes touch nothing.</summary>
        public static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && File.ReadAllText(path) == content)
                return false;
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content);
            return true;
        }
    }
}
