//<auto-generated/> FQS view facade — regenerate via Tools/FairyGUI/Bake Packages (FQS)
//source: VirtualList/Main (ui://qkteqwfpc8s20)
namespace FairyGUI.Baked.VirtualList
{
    public partial class MainView
    {
        public readonly global::FairyGUI.GComponent com;

        public readonly global::FairyGUI.GImage m_n0;
        public readonly global::FairyGUI.GImage m_n1;
        public readonly global::FairyGUI.GImage m_n2;
        public readonly global::FairyGUI.GList m_mailList;
        public readonly global::FairyGUI.GTextField m_n4;
        public readonly global::FairyGUI.GButton m_n6;
        public readonly global::FairyGUI.GButton m_n7;
        public readonly global::FairyGUI.GButton m_n8;

        public MainView(global::FairyGUI.GComponent c)
        {
            com = c;
            m_n0 = (global::FairyGUI.GImage)c.GetChildAt(0);
            m_n1 = (global::FairyGUI.GImage)c.GetChildAt(1);
            m_n2 = (global::FairyGUI.GImage)c.GetChildAt(2);
            m_mailList = (global::FairyGUI.GList)c.GetChildAt(3);
            m_n4 = (global::FairyGUI.GTextField)c.GetChildAt(4);
            m_n6 = (global::FairyGUI.GButton)c.GetChildAt(5);
            m_n7 = (global::FairyGUI.GButton)c.GetChildAt(6);
            m_n8 = (global::FairyGUI.GButton)c.GetChildAt(7);
        }

        public void SetPage(int controllerIndex, int pageIndex)
        {
            switch (controllerIndex)
            {
                default: com.GetControllerAt(controllerIndex).selectedIndex = pageIndex; break;
            }
        }
    }
}
